# Generated by Django 4.2 on 2023-04-17 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_over_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='over_view',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
