# Generated by Django 4.2 on 2023-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
