# Generated by Django 4.1.6 on 2023-02-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="feature",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
