# Generated by Django 4.1.6 on 2023-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="profile_picture",
            field=models.ImageField(default=True, upload_to=""),
            preserve_default=False,
        ),
    ]
