# Generated by Django 4.1.6 on 2023-02-13 07:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default="test", verbose_name="Content"),
            preserve_default=False,
        ),
    ]
