# Generated by Django 4.1.6 on 2023-02-13 08:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_remove_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default=True),
        ),
    ]
