# Generated by Django 4.1.6 on 2023-02-13 08:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=tinymce.models.HTMLField(),
        ),
    ]
