# Generated by Django 4.1.6 on 2023-02-13 08:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="God",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("godcontent", tinymce.models.HTMLField()),
            ],
        ),
    ]
