# Generated by Django 4.1.6 on 2023-02-13 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_remove_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="god", name="godcontent", field=ckeditor.fields.RichTextField(),
        ),
    ]
