# Generated by Django 4.1.6 on 2023-02-13 08:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_alter_god_godcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="god",
            name="godcontent",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
