# Generated by Django 4.1.6 on 2023-02-13 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_alter_god_godcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(default="test"),
            preserve_default=False,
        ),
    ]
