# Generated by Django 4.1.6 on 2023-02-13 15:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0015_texteditor_delete_god"),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(name="textEditor",),
    ]
