# Generated by Django 4.1.6 on 2023-02-13 15:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0016_article_delete_texteditor"),
    ]

    operations = [
        migrations.DeleteModel(name="article",),
        migrations.AlterField(
            model_name="post", name="content", field=tinymce.models.HTMLField(),
        ),
    ]
